name: Docker build & push
on: push   # quote 'on' to satisfy the YAML/GitHub schema linter
env:
  IMAGE_NAME: github-actions.nginx

jobs:
    Install-Docker:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install Docker
          run: |
            sudo apt-get update
            sudo apt-get install -y docker.io
    
   
        
         
    Run-Docker-Image:
      runs-on: ubuntu-latest
      
      steps:    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

    Push-Docker-Image:
       runs-on: ubuntu-latest
       
       steps:
          - name: Build and push Docker image
            uses: docker/build-push-action@v2
            with:
              context: .
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest
     